help_bridge = [
    "Explore available mental health support options:",
    "Check out the support you can access for your mental well-being:",
    "See what mental health help is available to you:",
    "Find out about the support you can get for your mental health:",
    "Discover available resources for your mental well-being:",
    "Learn about the help you can receive for your mental health:",
    "Explore available mental health assistance:",
    "Check out options for mental health support:",
    "See what mental health resources are accessible to you:",
    "Discover ways to get support for your mental well-being:",
    "Here are some ways to find support for your mental health:",
    "Explore available mental health resources:",
    "Discover support options for your well-being:",
    "Learn about the support you can access for your mental well-being:",
    "Explore these sources for mental health support:",
    "Discover ways to get help for your mental health here:",
    "Check out available resources for your mental well-being:",
    "Explore support services for your mental health needs:",
    "Here are some ways to get mental health support:",
    "Explore these resources for mental well-being:",
    "Check out these options for mental health help:",
    "See the support available for your mental health:",
    "Discover how you can access mental health care:",
    "Find out about these mental health support options:",
    "Learn about available help for your mental health:",
    "Check what mental health care is accessible:",
    "Explore available mental health support:",
    "Check out options for mental health help:",
    "Discover ways to get mental health support:",
    "Find assistance for your mental well-being:",
    "Learn about accessible mental health support:",
    "See what help is available for mental health:",
    "Explore support for your mental health needs:",
    "Discover sources of mental health assistance:",
    "Check what's there for mental health support:",
    "Find out about mental health care options:",
    "Explore available mental health support options:",
    "Check out the help you can find for mental well-being:",
    "See what mental health assistance is out there:",
    "Discover the support available for your mental health:",
    "Find accessible mental health care support:",
    "Learn about options for your mental health needs:",
    "See the mental health support that's available:",
    "Explore ways to get support for your mental health:",
    "Find out about available mental health assistance:",
    "Discover accessible mental health care options:"
]