not_depressed = [
    "I'm glad that you're feeling well. Remember to prioritize self-care, maintain healthy relationships, and engage in activities that bring you joy. If you ever start feeling overwhelmed, don't hesitate to seek support from friends or family.",
    "I'm genuinely pleased that you're not experiencing feelings of depression. It's essential to acknowledge and celebrate moments of emotional well-being. Remember, even on days when life feels relatively smooth, it's okay to express your emotions, be it joy, contentment, or any other positive sentiment. If there's anything specific you'd like to share or discuss, I'm here to listen and support you in navigating your thoughts and feelings.",
    "It's a relief to know that you're not currently grappling with feelings of depression. Embracing these moments of emotional stability is crucial for overall well-being. However, it's equally important to recognize that emotions can be dynamic, and I'm here for you, whether it's to explore your current positive state, discuss any challenges, or simply chat about anything on your mind. Your feelings, whatever they may be, are valid, and I'm here to provide support as you navigate through them.",
    "That's wonderful news that you're not feeling depressed right now. Embracing moments of emotional well-being is an important aspect of self-care. It's okay to relish in the positive moments, and I'm here to share in your joy. Whether you want to discuss your current state, share your accomplishments, or simply have a casual conversation, I'm here to engage with you and provide support in any way you need.",
    "I'm genuinely happy you're not currently experiencing depressive feelings. It's crucial to recognize and appreciate the times when emotions are more positive. While it's great to enjoy these moments, I want you to know that I'm here for you, not only during challenging times but also when things are going well. If there's anything specific you'd like to talk about or share",
    "I'm genuinely happy you're not currently experiencing feelings of depression. Acknowledging and embracing these moments of emotional well-being is essential. Even during times when life seems relatively smooth, it's completely okay to express your emotions, whether it's joy, contentment, or any other positive sentiment. If there's anything specific you'd like to share or discuss, please feel free to open up. I'm here to listen and support you as you navigate through your thoughts and feelings.",
    "I'm genuinely glad that you're not currently feeling depressed. It's a positive indicator of your emotional well-being. This state of mind can be empowering, allowing you to navigate your day with a sense of positivity. If there's anything on your mind that you'd like to share or discuss, feel free to let me know. I'm here to provide support and engage in conversation, whether it's about your experiences, interests, or anything else you'd like to talk about.",
    "It's truly wonderful news that you're not currently experiencing feelings of depression. This state of emotional well-being is valuable, and I hope you're able to relish in the positivity. If there's anything specific you'd like to discuss or share about your recent experiences or interests, I'm here to listen. Your thoughts and feelings are important, and I'm here to provide support in any way you need.",
    "I'm genuinely happy to know that you're not dealing with depression at the moment. Moments like these are opportunities to appreciate the positive aspects of life. Whether it's the simple joys of the day or any noteworthy events, it's great that you're experiencing a positive state. If there's anything you'd like to talk about or share, I'm here to provide support and engage in a conversation that suits your comfort.",
    "Not feeling depressed is a positive state, and I'm here to acknowledge and celebrate that with you. If there's anything exciting or noteworthy happening in your life that you'd like to discuss, or if you simply want to share your thoughts on anything specific, feel free to let me know. I'm here to provide support and engage in conversation based on your preferences.",
    "I'm pleased that you're not currently experiencing depressive feelings. Maintaining a positive outlook can be quite empowering. If there's anything you'd like to express or share, whether it's related to your current positive state or any other topic on your mind, I'm here to listen. Your thoughts and feelings are valid, and I'm ready to provide support in any way that feels right for you.",
    "It's truly uplifting to know that you're not feeling depressed right now. This positive state opens up opportunities for various experiences. If there's something specific you'd like to share or discuss, or if there's a particular aspect of your life that's contributing to this positive mood, I'm here to provide support and engage in a conversation tailored to your preferences.",
    "I'm genuinely pleased to learn that you're not currently experiencing feelings of depression. Your emotional well-being is important, and I hope you find moments of joy and fulfillment in your day. If there's anything you'd like to share or discuss, whether it's related to your positive experiences or anything else on your mind, I'm here for you.",
    "That's wonderful news that you're not feeling depressed right now. This positive state provides an opportunity to focus on the aspects of life that bring you happiness. If there's a specific interest or activity that uplifts your spirits, feel free to share. I'm always here with you.",
    "I'm genuinely happy to hear that you're not dealing with feelings of depression at the moment. Your well-being matters, and I hope you're able to enjoy moments of peace and contentment. If there's a particular aspect of your life that you find particularly fulfilling, I'd love to hear more about it. Feel free to share what brings positivity to your days.",
    "It's truly uplifting to know that you're not feeling depressed right now. Embracing these moments of emotional well-being is important, and I hope you find satisfaction in the positive aspects of your life. If there's anything you'd like to express or discuss, whether it's related to your experiences or interests, I'm here to provide support.",
    "I'm genuinely delighted to learn that you're not currently experiencing feelings of depression. This positive state allows for reflection on the bright moments in your life. If there's a specific achievement or accomplishment you'd like to share, I'm here to celebrate with you. Your successes, no matter how small, are significant.",
    "That's fantastic news! Not experiencing depression is a positive step forward. I hope you're able to bask in the positivity of the moment. If there's anything you'd like to talk about or share, whether it's related to your current mood or any other topic, I'm here to provide support to you!.",
    "I'm genuinely glad to know that you're not dealing with feelings of depression at the moment. Your emotional well-being is a priority, and I hope you continue to experience moments of peace and joy. If there's a particular hobby or interest that contributes to your positive state, I'd love to hear more about it. Feel free to share what brings fulfillment to your days.",
    "It's heartening to hear that you're not currently feeling depressed. This positive state offers a chance to focus on self-care and the things that make you happy. If there's anything you'd like to discuss or share, whether it's related to your current positive experiences or any other topic, I'm here to provide support and engage in a conversation that resonates with you.",
    "I'm genuinely pleased to hear that you're not experiencing feelings of depression right now. Your emotional well-being is significant, and I hope you find moments of serenity and happiness. If there's a specific aspect of your life that you'd like to highlight or discuss, I'm here to provide support and engage in a conversation that suits your preferences.",

    "That's fantastic! Not feeling depressed is a positive state, and I hope you're able to embrace the positivity of the moment. If there's anything you'd like to share or discuss, whether it's related to your current mood or any other topic, I'm always here",


    "I'm genuinely pleased to learn that you're not currently experiencing feelings of depression. Your emotional well-being is important, and I hope you find moments of joy and fulfillment in your day. Take time to appreciate these positive moments and celebrate the aspects of your life that bring happiness.",

    "That's wonderful news that you're not feeling depressed right now. This positive state provides an opportunity to focus on the aspects of life that bring you happiness. If there's a specific interest or activity that uplifts your spirits, feel free to share. Wishing you continued moments of positivity and contentment.",

    "I'm genuinely happy that you're not dealing with feelings of depression at the moment. Your well-being matters, and I hope you're able to enjoy moments of peace and contentment. If there's a particular aspect of your life that you find particularly fulfilling, I'd love to hear more about it. May you continue to find positivity in your days.",

    "It's truly uplifting to know that you're not feeling depressed right now. Embracing these moments of emotional well-being is important, and I hope you find satisfaction in the positive aspects of your life. If there's anything you'd like to express or discuss, whether it's related to your experiences or interests, take the time to reflect on those positive moments.",

    "I'm genuinely delighted to learn that you're not currently experiencing feelings of depression. This positive state allows for reflection on the bright moments in your life. If there's a specific achievement or accomplishment you'd like to share, I'm here to celebrate with you. Your successes, no matter how small, are significant.",

    "Not experiencing depression is a positive step forward. I hope you're able to bask in the positivity of the moment. If there's anything you'd like to talk about or share, whether it's related to your current mood or any other topic, take the time to appreciate the positive aspects of your life.",

    "I'm genuinely glad to know that you're not dealing with feelings of depression at the moment. Your emotional well-being is a priority, and I hope you continue to experience moments of peace and joy. If there's a particular hobby or interest that contributes to your positive state, take the time to indulge in those activities.",

    "It's heartening that you're not currently feeling depressed. This positive state offers a chance to focus on self-care and the things that make you happy. If there's anything you'd like to discuss or share, whether it's related to your current positive experiences or any other topic, feel free to reflect on those positive moments.",

    "I'm genuinely pleased to hear that you're not experiencing feelings of depression right now. Your emotional well-being is significant, and I hope you find moments of serenity and happiness. If there's a specific aspect of your life that you'd like to highlight or discuss, take the time to savor the positivity in your days.",

    "That's fantastic! Not feeling depressed is a positive state, and I hope you're able to embrace the positivity of the moment. If there's anything you'd like to share or discuss, whether it's related to your current mood or any other topic, remember to take a moment to appreciate the positive aspects of your life.",

    "I'm genuinely pleased to learn that you're not currently experiencing feelings of depression. Recognizing and embracing these moments of emotional well-being is a significant aspect of your journey. I sincerely hope that these positive occurrences continue to illuminate your days, bringing a sense of fulfillment and joy to various aspects of your life.",

    "That's wonderful news that you're not feeling depressed right now. This positive state provides a unique opportunity to focus on the aspects of life that genuinely bring you happiness. Whether it's engaging in specific interests, spending time with loved ones, or immersing yourself in activities that uplift your spirits, I encourage you to indulge in these moments of joy, fostering a sense of contentment in your daily life.",

    "I'm genuinely happy that you're not currently dealing with feelings of depression. Your well-being is of paramount importance, and I hope you're able to relish in these moments of peace and contentment. Take the time to appreciate the positive aspects of your life, reflecting on the elements that contribute to your overall happiness and satisfaction.",

    "It's truly uplifting to know that you're not feeling depressed right now. These periods of emotional well-being are crucial, offering a chance to find satisfaction in the positive aspects of your life. Whether it's the pursuit of personal goals, the enjoyment of hobbies, or the strengthening of meaningful relationships, I encourage you to savor and celebrate these moments of positivity.",

    "I'm genuinely delighted to learn that you're not currently experiencing feelings of depression. This positive state creates a space for reflection on the bright moments in your life. If there are specific achievements or accomplishments that have contributed to this positive mood, take pride in these successes, acknowledging the significance they hold in shaping your well-being.",

    "Not experiencing depression is a notable step forward on your journey. I hope you're able to bask in the positivity of the moment, recognizing and appreciating the good things that currently surround you. May these positive occurrences serve as a source of strength and encouragement as you navigate through various facets of your life.",

    "I'm genuinely glad to know that you're not dealing with feelings of depression at the moment. Your emotional well-being is a priority, and I hope you continue to experience moments of peace and joy. Take this time to nurture your mental and emotional health, indulging in activities and practices that contribute to your overall sense of well-being.",

    "It's heartening that you're not currently feeling depressed. This positive state offers a chance to focus on self-care and the things that bring you genuine happiness. As you navigate through these moments, consider indulging in activities that bring joy, fostering a sense of fulfillment and balance in your daily routine.",

    "I'm genuinely pleased that you're not experiencing feelings of depression right now. Your emotional well-being holds significant value, and I hope you find moments of serenity and happiness in various aspects of your life. Take the time to appreciate the positive connections, experiences, and personal achievements that contribute to your overall sense of contentment.",

    "Not feeling depressed is a positive state, and I hope you're able to embrace the positivity of the moment. In this phase of emotional well-being, take a moment to reflect on and appreciate the positive aspects of your life. Whether it's personal accomplishments, meaningful relationships, or moments of joy, acknowledge these elements as vital contributors to your overall happiness.",

    "It's wonderful to sense that you're currently in a positive state. Embracing these moments of emotional well-being is important, and taking time to indulge in activities that bring you joy or spending quality moments with loved ones can be uplifting for your overall mood.",

    "I'm glad to pick up on the positive vibes in your current experience. Recognizing and celebrating these moments of contentment is crucial. Engaging in activities that make you happy and focusing on the positive aspects of your life can contribute to your overall sense of well-being.",

    "It's heartening to sense that you're not carrying the weight of emotional distress right now. Embracing these moments of tranquility is significant. Consider taking a moment to appreciate the simple joys in your life and allowing yourself to bask in the positivity of your current emotional state.",

    "I'm pleased to pick up on the positive energy in your current emotional landscape. These moments of well-being are valuable, and finding time for self-care, enjoying your favorite activities, or connecting with positive influences can contribute to maintaining this positive outlook.",

    "It's truly uplifting to sense that you're not currently experiencing emotional challenges. Recognizing and savoring these moments of emotional stability is crucial for overall well-being. Consider indulging in activities that bring joy and embracing the positive aspects of your life.",

    "I'm glad to sense that you're in a positive emotional space right now. Taking the time to acknowledge and appreciate these moments of well-being is important. Engaging in activities that bring you comfort and connecting with positive aspects of your life can contribute to maintaining this positive state.",

    "It's wonderful to pick up on the positive vibes in your current experience. These moments of emotional well-being are valuable, and nurturing connections with loved ones or finding joy in your favorite activities can help sustain this positive outlook.",

    "I'm pleased to sense that you're not currently facing emotional distress. Recognizing and celebrating these moments of contentment is important. Taking the time to engage in activities that bring joy or spending quality moments with loved ones can contribute to maintaining this positive emotional state.",

    "It's heartening to pick up on the positive energy in your current emotional landscape. Embracing these moments of tranquility is significant. Consider taking a moment to appreciate the simple joys in your life and allowing yourself to bask in the positivity of your current emotional state.",

    "I'm glad to sense that you're in a positive emotional space right now. Recognizing and savoring these moments of emotional well-being is crucial for overall well-being. Engaging in activities that bring you comfort and connecting with positive aspects of your life can contribute to maintaining this positive state."
]