welcoming_messages = [
   "Hello there! I'm HealtEase, your friendly guide to mental wellness. How can I help you today?",
   "Hi there! Ready to prioritize your well-being? I'm here to support you every step of the way.",
   "Warm greetings! I'm HealtEase, here to help you navigate your health journey with ease. What's on your mind?",
   "Welcome! Let's explore a world of possibilities together. I'm excited to help you create a healthier, happier life.",
   "Hello! It's a joy to connect with you. I'm here to listen, offer guidance, and cheer you on towards happier life.",
   "Hey there! Feeling a bit under the weather? Or maybe just looking to boost your overall wellness? I'm here for you!",
   "Greetings! I'm HealtEase. Let's chat!",
   "I'm HealtEase, your personal mental health assistant. How can I make your day a little healthier?",
   "Hello there! Feeling stressed? Overwhelmed? Or just ready to make some positive changes? I'm here to help you find your ease.",
   "Hi there! I'm HealtEase, your virtual wellness buddy. Let's team up to create a healthier and happier you!",
   "Welcome! I'm here to help you take charge of your health and well-being. What would you like to focus on today?",
   "Welcome to your one-stop health resource! I'm HealtEase, here to provide information, support, and motivation.",
   "Hello there! I'm HealtEase, your 24/7 health support system. No matter what you're facing, I'm here for you.",
   "Greetings! I'm HealtEase, your guide to a healthier, happier, and more fulfilling life. Let's start your journey today!",
   "Hi there! I'm HealtEase, ready to provide you with personalized health advice and support. Let's work together to reach your wellness goals!",
   "Hi! I'm HealtEase, your friendly companion for feeling good. How can I help you today?",
   "Welcome! Looking for ways to boost your mood and overall well-being? I'm HealtEase, here to help you shine.",
   "Hey there! Feeling a bit underwhelmed? I'm HealtEase, ready to share some tips for living your best life.",
   "Greetings! Let's explore ways to create a happier, healthier you. I'm HealtEase, your supportive guide.",
   "Welcome to your personal well-being haven! I'm HealtEase, here to help you prioritize self-care and feel amazing.",
   "Hi there! Mood feeling blue? I'm HealtEase, ready to share some sunshine and tips for emotional recharge.",
   "Hello! Looking for inspiration to live a brighter day? I'm HealtEase, your cheerleader for well-being.",
   "Welcome! It's a joy to connect with you. I'm HealtEase, ready to provide simple tips for a happier, healthier you.",
   "Hey there! Feeling burnt out? I'm HealtEase, here to help you unwind and find your inner calm.",
   "Greetings! Let's explore ways to feel your best, inside and out. I'm HealtEase, your personalized well-being guide.",
   "Welcome! Feeling inspired to create positive changes? I'm HealtEase, your partner in creating a happier, healthier future.",
   "Hi there! Need a little sunshine for your soul? I'm HealtEase, ready to share some positivity and tips for emotional well-being.",
   "Hello! Want to feel more energized and vibrant? I'm HealtEase, your supporter for finding your inner spark.",
   "Welcome! Let's chat about healthy habits and simple ways to feel your best. I'm HealtEase, your well-being cheerleader.",
   "Hey there! Looking for ways to reduce stress and find inner peace? I'm HealtEase, your guide to calming your mind and spirit.",
   "Greetings! Want to learn some self-care secrets for a happier, healthier you? I'm HealtEase, here to share the magic.",
   "Welcome! Feeling motivated to make positive changes? I'm HealtEase, your partner in creating a life you love.",
   "Hi there! Need a little boost of positivity? I'm HealtEase, ready to share some sunshine and inspiration for your well-being journey.",
   "Hello! Let's explore ways to nurture your mental and emotional well-being. I'm HealtEase, your supportive guide on this journey.",
   "Welcome! Feeling ready to prioritize your happiness and self-care? I'm HealtEase, your cheerleader for creating a life you love.",
    "Hey there! Ready to prioritize your happiness? I'm HealtEase, your supportive guide to a brighter mood.",
   "Welcome! Let's chat about simple ways to boost your well-being and feel your best. I'm here to help you shine.",
   "Hello! Feeling a bit stressed or overwhelmed? I'm HealtEase, ready to share tips for finding calm and ease.",
   "Greetings! Looking to create a healthier, happier lifestyle? I'm here to support you on your journey.",
   "Welcome to your personal wellness corner! I'm HealtEase, your guide to feeling good and living well.",
   "Hi there! Need a little motivation to make positive changes? I'm here to cheer you on and offer inspiration.",
   "Hello! Want to explore simple ways to boost your mood and energy? I'm HealtEase, your partner in wellness.",
   "Welcome! Feeling ready to prioritize self-care? I'm here to help you create a life you love.",
   "Hey there! Looking for tips to reduce stress and find inner peace? I'm HealtEase, your guide to calm and serenity.",
   "Hi there! Need a little help managing anxiety or negative thoughts? I'm here to offer gentle guidance.",
   "Hello! Let's explore strategies for building resilience and emotional strength. I'm HealtEase, your supportive coach.",
   "Welcome! Feeling ready to create a more balanced and fulfilling life? I'm here to help you design your wellness plan.",
   "Hey there! Looking for ways to connect with nature and nurture your soul? I'm HealtEase, your guide to mindful living.",
   "Greetings! Want to discover simple ways to practice gratitude and cultivate joy? I'm here to share inspiration.",
   "Hi there! Need a little boost of encouragement to reach your wellness goals? I'm here to support you every step of the way.",
   "Hello! Let's take a journey together towards a happier, healthier you. I'm HealtEase, your guide and companion."
]
